### ISSUE TITLE
No documenation for filter_query

### ISSUE THREAD

**Issue by thomasedwards** [storyblok/storyblok-ruby#12]
How do I use a `filter_query` when fetching stories?

Tried using

    stories = storyblok_client.stories(
      "filter_query[first_published_at][lt_date]": DateTime.now.strftime('%Y-%m-%d %H:%M')
    )

But returns 0 results. I’ve also tried using `'%FT%T.%3NZ'` as the date format, but neither work.

**Comment by DominikAngerer** [comment]
Hey there! 

You can find filter query examples right here: https://www.storyblok.com/docs/api/content-delivery#examples/filtering/filters on the top right corner you can also select "ruby" for the examples.

Important to mention here is that filter query only works on your custom fields and not on the Story object itself. The query that you want to perform can be done by our default query parameters as those are default story properties: https://www.storyblok.com/cl/new-date-queries

```
stories = storyblok_client.stories(
  "first_published_at_lt": "2020-04-14 10:00"
)
```

**Comment by thomasedwards** [comment]
Amazing! Thanks!
