### ISSUE TITLE
Bad developer experience

### ISSUE THREAD

**Issue by wulffeld** [storyblok/storyblok-ruby#18]
First of all thank you for the work done already.

I've been playing around with Storyblok for a day and I quickly hit issues where I couldn't understand why the API wouldn't return newly published entries. Obviously I thought it was some caching thing going on so I tried the *flush* command to no avail. After finding https://www.storyblok.com/docs/guide/essentials/accessing-data I noticed the *cv* query parameter, figured it was a cache buster and tried to apply that to the stories call:

```
  client.stories(cv: Time.now.to_i)
```

Now I get back the response I would expect.

I think this should be documented here as the current default is surprising and not explained.

**Comment by christianzoppi** [comment]
Thanks @wulffeld . This issue is fixed and closed by #21, with the update to the V2 API as the default version for the client, which has an enhanced caching strategy.
