### ISSUE TITLE
A customer reported an issue with the SB RUBY client. He apparently gets always cached content without any change in their code and it worked before that without issues.

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok-ruby#19]
The customer mentioned that the ruby client gem seems to be broken as they're getting always the cached version.
Their code stopped working around the time the new API V2 showed up in our app menu.

This used to work for the customer:

Storyblok::Client.new(token: storyblok_preview_token, version: 'published',
cache_version: Time.now.to_i)"

**Comment by SxDx** [comment]
Probably also fixed with https://github.com/storyblok/storyblok-ruby/issues/17#issuecomment-898879680

**Comment by christianzoppi** [comment]
Thanks @SxDx. This issue is fixed and closed by #21, with the update to the V2 API as the default version for the client.

**Comment by christianzoppi** [comment]
Thanks @SxDx. This issue is fixed and closed by #21, with the update to the V2 API as the default version for the client.
