### ISSUE TITLE
Getting the right version and busting the cache

### ISSUE THREAD

**Issue by abrambailey** [storyblok/storyblok-ruby#2]
I had to make some modifications
```ruby
  def get_story_by_slug(slug, version)
    begin
      client = Storyblok::Client.new(token: storyblok_preview_token, version: version, cache_version: Time.now.to_i)
      return client.story(slug)
    rescue RestClient::NotFound
      return nil
    end
  end
```
Didn't realize it defaulted to draft version at first... So, now call `get_story_by_slug` with version `draft` or `published` ... Also, the published version was being cached, so I updated that (it was set in the defaults, but for some reason that wasn't having any effect).

**Comment by onefriendaday** [comment]
Hi!

We added the documentation of how to flush the cache and the default version:
https://github.com/storyblok/storyblok-ruby/blob/master/README.md#how-to-flush-the-cache
https://github.com/storyblok/storyblok-ruby/blob/master/README.md#usage
