### ISSUE TITLE
Fetching the very latest published content

### ISSUE THREAD

**Issue by jits** [storyblok/storyblok-ruby#8]
I'm trying understand how to apply [the recommended method for cache invalidation](https://www.storyblok.com/docs/api/content-delivery#topics/cache-invalidation) when fetching content from the API. This gets more complicated when using the local Redis caching too…

Setting an appropriate `cache_version` when instantiating the client (`Storyblok::Client.new`) makes sense. However, I'd like to reuse our client instance – would it be possible to update the internal `:cache_version` of the client instance? Maybe `client.flush` should do this automatically? Otherwise the flush itself isn't quite clearing all caches?

Would appreciate some guidance on how to go about fetching the very latest published content from the API, without having to re-instantiate the client each time.

**Comment by jits** [comment]
To add an observation: it seems that passing the cache version explicitly during the API operation (e.g `client.story`) is intended to be supported? However, there seems to be a mismatch in the query params here (i.e. `cache_version` vs `cv`):

https://github.com/storyblok/storyblok-ruby/blob/da33147a37d7c2685113fefabdba871071844759/lib/storyblok/client.rb#L223

**Comment by onefriendaday** [comment]
If you use redis it's recommended to setup a webhook in the Storyblok settings and call cache.flush on the receiving endpoint when something is published.

If you don't want to use webhooks you can add cache_version to every call and get the version from the client.space call.

~~~ruby
redis = Redis.new(host: redis_host, port: 6379)
cache = Storyblok::Cache::Redis.new(redis: redis)
client = Storyblok::Client.new(version: version,
                               token: token,
                               cache: cache)

uncached_client = Storyblok::Client.new(token: token)

cache_version = uncached_client.space['data']['space']['version']
client.stories({cache_version: cache_version})
~~~

**Comment by jits** [comment]
@onefriendaday – thanks for your suggestions.

Note: below is all in the context of using a _long lived_ instance of a `Storyblok::Client`, instead of instantiating a new client on every request.

> If you use redis it's recommended to setup a webhook in the Storyblok settings and call cache.flush on the receiving endpoint when something is published.

Unfortunately, calling `client.flush` does not mean you get the latest published content, as it doesn't reset [the internal `cache_version` value](https://github.com/storyblok/storyblok-ruby/blob/master/lib/storyblok/client.rb#L18) in that client instance – it just invalidates the Redis cache. Subsequent API calls to Storyblok still use the previous `cv` param in the API call, so won't fetch any newer published content.

The confusion here is due to "caching" in this gem really meaning two levels of caching:

1. (optional) Using Redis to cache content to avoid subsequent API calls to the Storyblok API.
1. Using the `cv` query param in the Storyblok API requests to control the newness of content.

The docs for the gem don't explain this well – there's an implicit assumption that "caching" is just one thing, but in practice seems to function differently (e.g. calling `client.flush` doesn't actually reset the `cache_version` in that client instance – something that could be fixed as part of the `client.flush` method [as per my original suggestion]?).

> If you don't want to use webhooks you can add cache_version to every call and get the version from the client.space call.

See https://github.com/storyblok/storyblok-ruby/issues/8#issuecomment-518313812 – my understanding is that the Storyblok API expects the query param to be `cv`, not `cache_version`, so your suggestion may not actually work as intended?

**Comment by freinbichler** [comment]
I just wasted more than 2 hours on fixing this before I saw this issue.

In the end, my workaround was the following:

```ruby
cache = Storyblok::Cache::Redis.new
client = Storyblok::Client.new(
  logger: Rails.logger,
  token: @token,
  cache_version: cache.get("storyblok:#{@token}:version"),
  cache: cache,
  version: 'published'
)
```

Please fix this, because as it is right now, calling `cache.flush` in the webhook doesn't actually get the most current content and is therefore quite useless.

**Comment by SxDx** [comment]
Possible fix: https://github.com/storyblok/storyblok-ruby/issues/17#issuecomment-898879680
